name: Prepare for release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Build production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true

      - name: Rocket.Chat Notification
        uses: iotechpis/Rocket.Chat.GitHub.Action.Notification@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: ':rocket: *Publish new release ${{ github.ref }}*'
          channel: '#develop'
          url: ${{ secrets.ROCKET_CHAT_WEBHOOK }}
